Lab10: Lab10.o
	g++ -o Lab10 Lab10.o -std=c++11

Lab10.o: Lab10.cpp d_galgs.h d_graph.h d_util.h d_except.h d_pqueue.h d_heap.h d_stree.h d_stiter.h
	g++ -c Lab10.cpp -std=c++11

clean:
	-rm *.o $(objects)