all: task1 task2 task3 task4 task5

task1: task1.c
	gcc -Wall task1.c -o task1

task2: task2.c
	gcc -Wall task2.c -o task2

task3: task3.c
	gcc -Wall task3.c -o task3

task4: task4.c
	gcc -Wall task4.c -o task4

task5: task5.c
	gcc -Wall task5.c -o task5

clean:
	rm task1 task2 task3 task4 task5