Lab11: Lab11.o
	g++ -o Lab11 Lab11.o -std=c++11

Lab11.o: Lab11.cpp d_galgs.h d_graph.h d_util.h d_except.h d_pqueue.h d_heap.h d_stree.h d_stiter.h
	g++ -c Lab11.cpp -std=c++11

clean:
	-rm *.o $(objects)