all: task1 twosum anyinput task3 task4 task5 task6

task1: task1.c
	gcc task1.c -o task1

twosum: twosum.c
	gcc twosum.c -o twosum

anyinput: anyinput.c
	gcc anyinput.c -o anyinput

task3: task3.c
	gcc -pthread task3.c -o task3

task4: task4.c
	gcc task4.c -o task4

task5: task5.c
	gcc -pthread task5.c -o task5

task6: task6.c
	gcc -pthread task6.c -o task6

clean:
	rm task1 twosum anyinput task3 task4 task5 task6