all: task1 twosum anyinput task3

task1: task1.c
	gcc task1.c -o task1

twosum: twosum.c
	gcc twosum.c -o twosum

anyinput: anyinput.c
	gcc anyinput.c -o anyinput

task3: task3.c
	gcc -pthread task3.c -o task3

clean:
	rm task1 twosum anyinput task3