all: process1 process2 task3 task4 pipeMult fact signals program1 program2

process1: process1.c
	gcc process1.c -o process1

process2: process2.c 
	gcc process2.c -o process2

task3: task3.c
	gcc task3.c -o task3

task4: task4.c
	gcc task4.c -o task4

pipeMult: pipeMult.c
	gcc pipeMult.c -o pipeMult

fact: fact.c
	gcc -pthread fact.c -o fact

signals: signals.c
	gcc signals.c -o signals

program1: program1.c
	gcc program1.c -o program1

program2: program2.c
	gcc program2.c -o program2
