all: task2a task2b task2c task3 task4a task4b task5

task2a: task2a.c
	gcc task2a.c -o task2a

task2b: task2b.c
	gcc task2b.c -o task2b

task2c: task2c.c
	gcc task2c.c -o task2c

task3: task3.c
	gcc task3.c -o task3

task4a: task4a.c
	gcc task4a.c -o task4a

task4b: task4b.c
	gcc task4b.c -o task4b

task5: task5.c
	gcc task5.c -o task5