all: task1 task2 task3 task5 task6 twosum anyinput 

task1: task1.c
	gcc task1.c -o task1

task2: task2.c
	gcc task2.c -o task2

task3: task3.c
	gcc -pthread task3.c -o task3

task5: task5.c	
	gcc -pthread task5.c -o task5

task6: task6.c
	gcc -pthread task6.c -o task6

twosum: twosum.c 
	gcc twosum.c -o twosum

anyinput: anyinput.c
	gcc anyinput.c -o anyinput


clean:
	rm task1 task2 task3 task5 task6 twosum anyinput 